### ISSUE TITLE
Nice Work

### ISSUE THREAD

**Issue by amordahl** [art160630/CS3354-NAHH#2]
Hi Team NAHH,

Nice work so far; everything looks good for your 0th milestone. However, one of your team members is showing up as 'unknown.' To that person, this means that 1) you haven't validated your email you used for your GitHub account yet, or 2) that your email is incorrect in your `.gitconfig` file. If the email in your `.gitconfig` file doesn't match one of the verified emails on your GitHub account, then GitHub won't be able to 'blame' you for your commits.

Just bringing this up because I need to be able to see who is making commits so I can give you credit for future submissions.

Thanks,
Austin

**Comment by art160630** [comment]
Thanks Austin! We'll make sure everyone is accounted for in the future.
